name: NCPExemptGeyser
version: ${project.version}
main: net.zejzz.ncpexemptgeyser.NCPExemptGeyser
api-version: 1.16
authors: [ Zejzz ]
description: Adds players who joined from Geyser to NCP ignore list
website: zejzz.net
